services:
  db:
    image: mysql:8.0
    container_name: issue-tracker-db
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - issue-network

networks:
  issue-network:
    driver: bridge