spring:
  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    aws:
      credentials:

        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: team01-issue-tracker-storage-2026