name: Backend CD

on:
  push:
    branches: [ "dev" ]
    paths-ignore:
      - "frontend/**"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. 도커 허브 로그인 (비밀번호 대신 토큰 사용)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 2. 도커 이미지 빌드 및 허브로 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/issue-tracker:latest

  deploy:
    needs: build-and-push # 빌드가 성공해야만 배포를 시작함
    runs-on: ubuntu-latest
    steps:
      # 3. EC2 서버 원격 접속 및 도커 컨테이너 교체
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker stop issue-tracker || true
            docker rm issue-tracker || true
            docker rmi ${{ secrets.DOCKER_USERNAME }}/issue-tracker:latest || true

            docker pull ${{ secrets.DOCKER_USERNAME }}/issue-tracker:latest
            
            docker run -d -p 8080:8080 \
              --name issue-tracker \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e DB_URL='${{ secrets.DB_URL }}' \
              -e DB_USERNAME='${{ secrets.DB_USERNAME }}' \
              -e DB_PASSWORD='${{ secrets.DB_PASSWORD }}' \
              ${{ secrets.DOCKER_USERNAME }}/issue-tracker:latest